version: 2
updates:
  - package-ecosystem: "pub"
    directory: "/packages/kiwi"
    schedule:
      interval: "daily"
    labels:
      - "pub.dev"
      - "kiwi"
      - "dependencies"
      
  - package-ecosystem: "pub"
    directory: "/packages/kiwi_generator"
    schedule:
      interval: "daily"
    labels:
      - "pub.dev"
      - "kiwi generator"
      - "dependencies"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "github actions"
      - "dependencies"